### ISSUE TITLE
Objects within slides

### ISSUE THREAD

**Issue by DemonDownUnder** [KevinBatdorf/liquidslider#64]
Attempting to embed an object onto a slide

Bar graph from here: http://www.abs.gov.au/ausstats/abs@.nsf/Products/8153.0~December+2012~Chapter~Type+of+access+connection?OpenDocument

Preview (3rd slide):
http://savethenbn.com/v2/test.html

Displays fine in chrome and IE but in firefox (v22.0) just a blank slate shows. Only leads i've found so far is this:

http://www.codezen.com/2009/03/swfobject-firefox-and-blank-screens-oh.html

can anyone help?

**Comment by clampdesign** [comment]
I am having this exact same problem. Just wondering if you might have figured out what is causing this? Thank you.

**Comment by KevinBatdorf** [comment]
Can you provide a link or even a code snippit? It's likely a CSS issue and could be a quick fix or something more complex. Also, it's working fine in Chrome but not FF?

**Comment by clampdesign** [comment]
I can't provide a link at the moment as I am working on this on my local server. That is correct that it is working in Chrome (and Safari) but not Firefox.  If I remember correctly, I didn't alter your CSS file except to remove the padding and background color (below):

`/*
 *  Liquid Slider v2
 *  Copyright 2012 Kevin Batdorf
 *  http://liquidslider.com
 *  MIT license
 */

.no-js .liquid-slider {
  height:auto;
  overflow:visible;
  text-align: center;
}
.no-js .liquid-slider div {
  margin-bottom: 20px;
  overflow: auto;
}
.ls-preloader {  
  background: url(../images/loading.gif) transparent no-repeat center 50%;
  opacity:1;
  width:100%;
  height:100%;
  position:absolute;
  top:0;
  left:0;
  z-index:2;
}

/*** Containers ***/
.ls-wrapper {
  clear: both;
  overflow: auto;
  position: relative;
}
.liquid-slider {
  /*background: #f2f2f2;*/
  width: 850px;
  margin: 0 auto;
  float: left;
  overflow: hidden;
  position: relative;
}
.arrows .liquid-slider {
  /* Margin between slider and arrows */
  margin: 0 10px;
}
.ls-responsive .liquid-slider {
  width: 100%;
  margin: 0;
}
.panel-container {
  position: relative;
  -webkit-backface-visibility: hidden;
  -webkit-perspective: 1000;
  /* from http://davidwalsh.name/translate3d */
}
.liquid-slider .panel-container .fade {
  width:100%;
  opacity: 0;
  position: absolute;
  top: 0; 
  left: 0;
  display: block;
}

/*** Panels ***/
.liquid-slider .panel {  
  width: 850px;
  display: block;
  float: left;
}
.panel-wrapper {  
/*  padding: 15px 40px; */  
position:relative;
}

/*** Tabbed Navigation ***/
.ls-nav {
  overflow:hidden;
  clear:both;
}
.ls-nav a {
  background: #d8d8d8;
  color: #333333;
  margin-right: 1px;
  padding: 10px 15px;  
  outline:0;
}
.ls-nav a:hover {
  background: #f2f2f2;
  color: #333333;
  text-shadow: none;
}
.ls-nav .current a {
  background: #f2f2f2;
}
.currentCrossLink {
  font-weight: bold;
}
.ls-nav ul {  
  padding:0;
  clear: both;
  display: block;
  margin: auto;
  overflow: hidden;
}
.ls-nav ul li {
  display: inline;
}
.ls-nav ul li a {
  display: block;
  float: left;
  text-decoration: none;
}

/*** Mobile Navigation ***/
.ls-select-box { 
  width: 100%;
  height: 35px;
  overflow: hidden;
  background: url(../images/menu.png) no-repeat right #ddd;
}
.ls-select-box select {  
  width: 150%;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance:none;
  background: transparent;
  padding: 5px;
  font-size: 110%;
  border: none;
  height: 35px;
  cursor:pointer;
  outline: 0;
}

/*** Arrow Navigation (non-graphical) ***/
.ls-nav-left, .ls-nav-right {
  float: left;
  clear:both;
}
.ls-nav-left a, .ls-nav-right a {
  background: #000;
  color: #fff;
  padding: 5px;
  width: 100px;
  display: block;
  text-align: center;
  text-decoration: none;
}
.ls-responsive .ls-nav-left {
  position: absolute;
  left: 0;
  z-index: 2;
}
.ls-responsive .ls-nav-left a {
  background: #9A9A9A;
  width: 80px;
}
.ls-responsive .ls-nav-left a:hover {
  background: #747474;
}
.ls-responsive .ls-nav-right {
  position: absolute;
  right: 0;
  z-index: 2;
}
.ls-responsive .ls-nav-right a {
  background: #9A9A9A;
  width: 80px;
}
.ls-responsive .ls-nav-right a:hover {
  background: #747474;
}

/*** Arrow Navigation (graphical) ***/
.ls-nav-left-arrow, .ls-nav-right-arrow {
  cursor: pointer;
  float: left;
  clear: both;
}
.ls-nav-left-arrow a, .ls-nav-right-arrow a {
  display: block;
  border-bottom: none !important;
}
[class$="-arrow"] {
  width: 25px;
  height: 25px;
  background-image: url(../images/arrow.png);
  background-repeat: no-repeat;
  margin-top: 50px;
  position:relative;
}
.ls-nav-right-arrow {
  background-position: top right;  
  margin-right: 5px;
}
.ls-nav-left-arrow {
  background-position: top left;  
  margin-left: 5px;
}
.ls-nav-left-arrow:hover {
  background-position: bottom left;
}
.ls-nav-right-arrow:hover {
  background-position: bottom right;
}
.ls-responsive .ls-nav-left-arrow {
  bottom:0;
  position: absolute;
  left: 0;
  z-index: 2;
}
.ls-responsive .ls-nav-right-arrow {
  bottom:0;
  position: absolute;
  right: 0;
  z-index: 2;
}`

The script to run the slider is a little more complex because I needed external linking with hash linking:

`    <script>
      $('#slideshow').liquidSlider({
          dynamicTabs: false,
          dynamicArrows: false,
          hoverArrows: false,
          hashTitleSelector: "span.slug",
          panelTitleSelector: "span.slug",
          hashLinking: true,
          slideEaseFunction: "easeInOutQuad",
          slideEaseDuration: 700,
          crossLinks:true,
          autoHeight: true,
          preloader: false,
      });
      var api2 = $.data( $('#slideshow')[0], 'liquidSlider');
      $('.enable-hash').on('click', function(e){
        e.preventDefault();
        api2.options.hashLinking = true;
        api2.buildHashTags();
        $(this).fadeOut();
      });

      // calculate the current and total number of slides and print to page
      $(function() {
        $( ".panel" ).not(".clone").each(function( index ) {
          $(this).attr('data-index', index + 1);
        });
        var totalSlides = $(".panel:not(.clone)").length;
        $('#totalSlides').text(totalSlides);
        var currentSlide = $('.currentPanel').not('.clone').attr('data-index');
        $('#currentSlide').text(currentSlide);
      });

      // When clicking on the external slide navigation, change the hashtag to the slug set up in artwork details (but hidden) and change the number of the current slide.
      $(function(){
        $(".slidenav").click(function(){
          var slide_href = $('.currentPanel').not('.clone').find('.artwork_details .slug').text();
          $(this).attr("href", "#" + slide_href);
          var currentSlide = $('.currentPanel').not('.clone').attr('data-index');
          $('#currentSlide').text(currentSlide);
        });
      });

    </script>`

I haven't added any other significant CSS. Just in case, I removed the entire style sheet for the site (just leaving your CSS) and the problem persists. Sometimes it just shows a blank black box, sometimes the title and play button show, but the cursor doesn't change and nothing is clickable. It feels like a z-index problem, but changing the z-index doesn't resolve anything. Sometimes, when I am navigating to the slide the poster image shows but as soon as it slides into place it is gone. 

When I have a little more time I'll try to do a test example on a public server.
If you have any thoughts in the meantime, let me know and I'll test them out. 

Thanks!

**Comment by clampdesign** [comment]
`    <script>

      $('#slideshow').liquidSlider({
          dynamicTabs: false,
          dynamicArrows: false,
          hoverArrows: false,
          hashTitleSelector: "span.slug",
          panelTitleSelector: "span.slug",
          hashLinking: true,
          slideEaseFunction: "easeInOutQuad",
          slideEaseDuration: 700,
          crossLinks:true,
          autoHeight: true,
          preloader: false,
      });
      var api2 = $.data( $('#slideshow')[0], 'liquidSlider');
      $('.enable-hash').on('click', function(e){
        e.preventDefault();
        api2.options.hashLinking = true;
        api2.buildHashTags();
        $(this).fadeOut();
      });

      // calculate the current and total number of slides and print to page
      $(function() {
        $( ".panel" ).not(".clone").each(function( index ) {
          $(this).attr('data-index', index + 1);
        });
        var totalSlides = $(".panel:not(.clone)").length;
        $('#totalSlides').text(totalSlides);
        var currentSlide = $('.currentPanel').not('.clone').attr('data-index');
        $('#currentSlide').text(currentSlide);
      });

      // When clicking on the external slide navigation, change the hashtag to the slug set up in artwork details (but hidden) and change the number of the current slide.
      $(function(){
        $(".slidenav").click(function(){
          var slide_href = $('.currentPanel').not('.clone').find('.artwork_details .slug').text();
          $(this).attr("href", "#" + slide_href);
          var currentSlide = $('.currentPanel').not('.clone').attr('data-index');
          $('#currentSlide').text(currentSlide);
        });
      });

    </script>`

**Comment by clampdesign** [comment]
I can't provide a link at the moment as I am working on this on my local server. That is correct that it is working in Chrome (and Safari) but not Firefox.  If I remember correctly, I didn't alter your CSS file except to remove the padding and background color (below):

```
.no-js .liquid-slider {
  height:auto;
  overflow:visible;
  text-align: center;
}
.no-js .liquid-slider div {
  margin-bottom: 20px;
  overflow: auto;
}
.ls-preloader {  
  background: url(../images/loading.gif) transparent no-repeat center 50%;
  opacity:1;
  width:100%;
  height:100%;
  position:absolute;
  top:0;
  left:0;
  z-index:2;
}

/*** Containers ***/
.ls-wrapper {
  clear: both;
  overflow: auto;
  position: relative;
}
.liquid-slider {
  /*background: #f2f2f2;*/
  width: 850px;
  margin: 0 auto;
  float: left;
  overflow: hidden;
  position: relative;
}
.arrows .liquid-slider {
  /* Margin between slider and arrows */
  margin: 0 10px;
}
.ls-responsive .liquid-slider {
  width: 100%;
  margin: 0;
}
.panel-container {
  position: relative;
  -webkit-backface-visibility: hidden;
  -webkit-perspective: 1000;
  /* from http://davidwalsh.name/translate3d */
}
.liquid-slider .panel-container .fade {
  width:100%;
  opacity: 0;
  position: absolute;
  top: 0; 
  left: 0;
  display: block;
}

/*** Panels ***/
.liquid-slider .panel {  
  width: 850px;
  display: block;
  float: left;
}
.panel-wrapper {  
/*  padding: 15px 40px; */  
position:relative;
}

/*** Tabbed Navigation ***/
.ls-nav {
  overflow:hidden;
  clear:both;
}
.ls-nav a {
  background: #d8d8d8;
  color: #333333;
  margin-right: 1px;
  padding: 10px 15px;  
  outline:0;
}
.ls-nav a:hover {
  background: #f2f2f2;
  color: #333333;
  text-shadow: none;
}
.ls-nav .current a {
  background: #f2f2f2;
}
.currentCrossLink {
  font-weight: bold;
}
.ls-nav ul {  
  padding:0;
  clear: both;
  display: block;
  margin: auto;
  overflow: hidden;
}
.ls-nav ul li {
  display: inline;
}
.ls-nav ul li a {
  display: block;
  float: left;
  text-decoration: none;
}

/*** Mobile Navigation ***/
.ls-select-box { 
  width: 100%;
  height: 35px;
  overflow: hidden;
  background: url(../images/menu.png) no-repeat right #ddd;
}
.ls-select-box select {  
  width: 150%;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance:none;
  background: transparent;
  padding: 5px;
  font-size: 110%;
  border: none;
  height: 35px;
  cursor:pointer;
  outline: 0;
}

/*** Arrow Navigation (non-graphical) ***/
.ls-nav-left, .ls-nav-right {
  float: left;
  clear:both;
}
.ls-nav-left a, .ls-nav-right a {
  background: #000;
  color: #fff;
  padding: 5px;
  width: 100px;
  display: block;
  text-align: center;
  text-decoration: none;
}
.ls-responsive .ls-nav-left {
  position: absolute;
  left: 0;
  z-index: 2;
}
.ls-responsive .ls-nav-left a {
  background: #9A9A9A;
  width: 80px;
}
.ls-responsive .ls-nav-left a:hover {
  background: #747474;
}
.ls-responsive .ls-nav-right {
  position: absolute;
  right: 0;
  z-index: 2;
}
.ls-responsive .ls-nav-right a {
  background: #9A9A9A;
  width: 80px;
}
.ls-responsive .ls-nav-right a:hover {
  background: #747474;
}

/*** Arrow Navigation (graphical) ***/
.ls-nav-left-arrow, .ls-nav-right-arrow {
  cursor: pointer;
  float: left;
  clear: both;
}
.ls-nav-left-arrow a, .ls-nav-right-arrow a {
  display: block;
  border-bottom: none !important;
}
[class$="-arrow"] {
  width: 25px;
  height: 25px;
  background-image: url(../images/arrow.png);
  background-repeat: no-repeat;
  margin-top: 50px;
  position:relative;
}
.ls-nav-right-arrow {
  background-position: top right;  
  margin-right: 5px;
}
.ls-nav-left-arrow {
  background-position: top left;  
  margin-left: 5px;
}
.ls-nav-left-arrow:hover {
  background-position: bottom left;
}
.ls-nav-right-arrow:hover {
  background-position: bottom right;
}
.ls-responsive .ls-nav-left-arrow {
  bottom:0;
  position: absolute;
  left: 0;
  z-index: 2;
}
.ls-responsive .ls-nav-right-arrow {
  bottom:0;
  position: absolute;
  right: 0;
  z-index: 2;
}
```

The script to run the slider is a little more complex because I needed external linking with hash linking:

```javascript
$('#slideshow').liquidSlider({
    dynamicTabs: false,
    dynamicArrows: false,
    hoverArrows: false,
    hashTitleSelector: "span.slug",
    panelTitleSelector: "span.slug",
    hashLinking: true,
    slideEaseFunction: "easeInOutQuad",
    slideEaseDuration: 700,
    crossLinks:true,
    autoHeight: true,
    preloader: false,
});
var api2 = $.data( $('#slideshow')[0], 'liquidSlider');
$('.enable-hash').on('click', function(e){
  e.preventDefault();
  api2.options.hashLinking = true;
  api2.buildHashTags();
  $(this).fadeOut();
});

// calculate the current and total number of slides and print to page
$(function() {
  $( ".panel" ).not(".clone").each(function( index ) {
    $(this).attr('data-index', index + 1);
  });
  var totalSlides = $(".panel:not(.clone)").length;
  $('#totalSlides').text(totalSlides);
  var currentSlide = $('.currentPanel').not('.clone').attr('data-index');
  $('#currentSlide').text(currentSlide);
});

// When clicking on the external slide navigation, change the hashtag to the slug set up in artwork details (but hidden) and change the number of the current slide.
$(function(){
  $(".slidenav").click(function(){
    var slide_href = $('.currentPanel').not('.clone').find('.artwork_details .slug').text();
    $(this).attr("href", "#" + slide_href);
    var currentSlide = $('.currentPanel').not('.clone').attr('data-index');
    $('#currentSlide').text(currentSlide);
  });
});
```


I haven't added any other significant CSS. Just in case, I removed the entire style sheet for the site (just leaving your CSS) and the problem persists. Sometimes it just shows a blank black box, sometimes the title and play button show, but the cursor doesn't change and nothing is clickable. It feels like a z-index problem, but changing the z-index doesn't resolve anything. Sometimes, when I am navigating to the slide the poster image shows but as soon as it slides into place it is gone. 

When I have a little more time I'll try to do a test example on a public server.
If you have any thoughts in the meantime, let me know and I'll test them out. 

Thanks!

**Comment by KevinBatdorf** [comment]
Try setting continuous:false

**Comment by clampdesign** [comment]
I did that already. No change, unfortunately.

On Mon, Feb 9, 2015 at 1:24 PM, Kevin Batdorf <notifications@github.com>
wrote:

> Try setting continuous:false
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KevinBatdorf/liquidslider/issues/64#issuecomment-73500253>
> .
>



-- 
Best,
Laura




Laura Yeffeth
646 845 9125
skype: laurayeffeth
www.clampdesign.com
